version: 2.1
jobs:
  build:
    docker: 
      - image: cimg/base:2020.01
    steps:
      - checkout # check out the code in the project directory
      - run: echo "hello world" # run the `echo` command
  validate:
    docker:
      - image: cimg/base:2020.01
    steps:
      - checkout

workflows:
  version: 2
  one_and_two:
    jobs:
      - build
      - validate:
        requires:
          - build
