version: 2.1
jobs:
  init:
    docker: 
      - image: cimg/base:2020.01
    steps:
      - checkout # check out the code in the project directory
      - run: echo "hello world" # run the `echo` command
