jobs:
  build:
    docker: 
      - image: cimg/base:2020.01
    steps:
      - checkout # check out the code in the project directory
      - run: echo "hello world" # run the `echo` command
  validate:
    docker:
      - image: cimg/base:2020.01
    steps:
      - checkout

version: 2
workflows:
  build_validate:
    jobs:
      - build
      - validate:
        requires:
          - build