version: 2.1
commands:
  init:
    parameters:
      command:
        type: string
    steps:
      - run:
          name: Init
          command: "echo << parameters.init >>"
executors:
  terraform:
    docker:
      - image: hashicorp/terraform:0.12.24
jobs:
  init:
    executor: terraform
    steps:
      - init:
          command: "init"
